import "./globals.css";
import type { Metadata } from "next";
import { LayoutProvider, NextAuthProvider } from "./providers";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="w-screen min-h-screen bg-neutral-200">
        <NextAuthProvider>
          <LayoutProvider>{children}</LayoutProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
